version: '3.8'

services:
  traewelling-metrics:
    build:
      context: go/.
      dockerfile: Dockerfile
      #no_cache: true
    #ports:
    #  - "8080:8080" # Exponiere Port 8080 für Prometheus-Scraping
    restart: always # Neustart bei Fehlern oder Updates
    environment:
      - TRAEWELLING_TOKEN=${TRAEWELLING_TOKEN}
      - TRAEWELLING_USERNAMES=${TRAEWELLING_USERNAMES}
    networks:
      default:
      dns:
        ipv4_address: 172.28.0.245

networks:
  dns:
    external: true
