{
 "title": "Träwelling",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(traewelling_total_train_duration_minutes,job)"
    }
   },
   {
    "name": "user",
    "label": "Benutzer",
    "query": {
     "query": "label_values(traewelling_total_points{job=\"$job\"},username)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Gesamte Zugdauer pro Benutzer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"$job\", __name__=\"traewelling_total_train_duration_minutes\", username=\"$user\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gesamte Zugstrecke pro Benutzer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "suffix: km" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"$job\", __name__=\"traewelling_total_train_distance_km\", username=\"$user\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gesamtpunkte pro Benutzer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"$job\", __name__=\"traewelling_total_points\", username=\"$user\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gesamte Zugstrecke pro Benutzer (Total)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "suffix: km" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"$job\", __name__=\"traewelling_total_train_distance_km\"}",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Gesamte Zugdauer pro Benutzer (Total)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"$job\", __name__=\"traewelling_total_train_duration_minutes\"}",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Gesamtpunkte pro Benutzer (Total)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"$job\", __name__=\"traewelling_total_points\"}",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Aktuelle Zugstatus der einzelnen Personen",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"$job\", __name__=\"traewelling_current_train_statuses\", username=\"$user\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}